### ISSUE TITLE
Add / Fix tileset for map

### ISSUE THREAD

**Issue by lecoqjacob** [lecoqjacob/bevy_jam_2_2022#8]
Adjust tilset to better fit game needs. Either find and replace current tileset or mix and match tilesets to get the right feel

**Dev Help**
[Kenny 2D Packs](https://www.kenney.nl/assets)

**Comment by james-mallory** [comment]
Added 4 kenny tilesets to use along with our current set from 'Dawnlike'. We'll be able to easily improve on the map using these tilesets.
